### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gischupa** [kantel/kantel.github.io#58]
Hi, 
schwer ein Feedback ohne Formular :) Zumindest hab ich keines gefunden.
Hab schnell mal dein "AlienAttack" auf Linux anprobiert. hab nicht alle Varianten getestet, aber augenscheinlich klappt alles ... Weiter viel Spaß damit ...
Überlag gerade, ob ich das in der Schule irgenwo sinnstiftend einsetzen kann.
Problem wird etwas die "Bebilderung" werden :)

VG
Wolfgang

**Comment by kantel** [comment]
Tut mir leid, aber Giskus, mein Kommentarsystem, war leider für ein paar Stunden ausgefallen.

Was die »Bebilderung« betrifft: Ich habe in dem konkreten Beispiel die Figuren mit dem freien Avatar-Generator »[Framiq](https://framiq.com/)« zusammengebastelt und für die Hintergrundbilder das »[[Visual Novel Backgrounds Office_BG Set](https://quarkyifu.itch.io/visual-novel-backgrounds-office-bg-set)« verwendet. (Momentan tendiere ich allerdings mehr dazu, dafür eigenen Photos zu verwenden.) Und [diese Seite](https://itch.io/game-assets/free/genre-visual-novel) auf Itch.io bietet »Tonnen« von frei verwendbaren Material an – man muß nur suchen.

Ich plane, dazu auch einen separaten Blogbeitrag zu schreiben (das wird allerdings noch dauern). Daher kann ich zum Einstieg erst einmal nur [diesen (meinen) Beitrag](https://kantel.github.io/posts/2022122102_alien_invasion_stage_1/) anbieten.

**Comment by gischupa** [comment]
Hi, 
werd ich (wenn Zeit) sicher überall mal rein sehen ... aber wie ein weiser Mann einmal sagte: So viel zu spielen, so wenig Zeit! :)
